export const countryCodeList = [
  { url: "/AF", name: "Afghanistan" },
  { url: "/AL", name: "Albania" },
  { url: "/DZ", name: "Algeria" },
  { url: "/AS", name: "America Samoa" },
  { url: "/AD", name: "Andorra" },
  { url: "/AO", name: "Angola" },
  { url: "/AI", name: "Anguilla" },
  { url: "/AQ", name: "Antarctica" },
  { url: "/AG", name: "Antigua and Barbuda" },
  { url: "/AR", name: "Argentina" },
  { url: "/AM", name: "Armenia" },
  { url: "/AW", name: "Aruba" },
  { url: "/AU", name: "Australia" },
  { url: "/AT", name: "Austria" },
  { url: "/AZ", name: "Azerbaijan" },
  { url: "/BS", name: "Bahamas" },
  { url: "/BH", name: "Bahrain" },
  { url: "/BD", name: "Bangladesh" },
  { url: "/BB", name: "Barbados" },
  { url: "/BY", name: "Belarus" },
  { url: "/BE", name: "Belgium" },
  { url: "/BZ", name: "Belize" },
  { url: "/BJ", name: "Benin" },
  { url: "/BM", name: "Bermuda" },
  { url: "/BT", name: "Bhutan" },
  { url: "/BO", name: "Bolivia" },
  { url: "/BA", name: "Bosnia and Herz." },
  { url: "/BW", name: "Botswana" },
  { url: "/BR", name: "Brazil" },
  { url: "/BN", name: "Brunei" },
  { url: "/BG", name: "Bulgaria" },
  { url: "/BF", name: "Burkina Faso" },
  { url: "/BI", name: "Burundi" },
  { url: "/CV", name: "Cabo Verde	" },
  { url: "/KH", name: "Cambodia" },
  { url: "/CM", name: "Cameroon" },
  { url: "/CA", name: "Canada" },
  { url: "/CF", name: "Central African Rep." },
  { url: "/TD", name: "Chad" },
  { url: "/CL", name: "Chile" },
  { url: "/CN", name: "China" },
  { url: "/CO", name: "Colombia" },
  { url: "/CG", name: "Congo" },
  { url: "/CR", name: "Costa Rica" },
  { url: "/HR", name: "Croatia" },
  { url: "/CU", name: "Cuba" },
  { url: "/CY", name: "Cyprus" },
  { url: "/CZ", name: "Czechia" },
  { url: "/CI", name: "Côte d'Ivoire" },
  { url: "/DK", name: "Denmark" },
  { url: "/DJ", name: "Djibouti" },
  { url: "/DO", name: "Dominican Rep." },
  { url: "/EC", name: "Ecuador" },
  { url: "/EG", name: "Egypt" },
  { url: "/SV", name: "El Salvador" },
  { url: "/GQ", name: "Eq. Guinea	" },
  { url: "/ER", name: "Eritrea" },
  { url: "/EE", name: "Estonia" },
  { url: "/SZ", name: "Eswatini" },
  { url: "/ET", name: "Ethiopia" },
  { url: "/FK", name: "Falkland Is." },
  { url: "/FJ", name: "Fiji" },
  { url: "/FI", name: "Finland" },
  { url: "/FR", name: "France" },
  { url: "/TF", name: "Fr. S. Antarctic Lands" },
  { url: "/GA", name: "Gabon" },
  { url: "/GM", name: "Gambia" },
  { url: "/GE", name: "Georgia" },
  { url: "/DE", name: "Germany" },
  { url: "/GH", name: "Ghana" },
  { url: "/GI", name: "Gibraltar" },
  { url: "/GR", name: "Greece" },
  { url: "/GL", name: "Greenland" },
  { url: "/GT", name: "Guatemala" },
  { url: "/GN", name: "Guinea" },
  { url: "/GY", name: "Guyana" },
  { url: "/HT", name: "Haiti" },
  { url: "/HN", name: "Honduras" },
  { url: "/HK", name: "Hong Kong" },
  { url: "/HU", name: "Hungary" },
  { url: "/IS", name: "Iceland" },
  { url: "/IN", name: "India" },
  { url: "/ID", name: "Indonesia" },
  { url: "/IR", name: "Iran" },
  { url: "/IQ", name: "Iraq" },
  { url: "/IE", name: "Ireland" },
  { url: "/IL", name: "Israel" },
  { url: "/IT", name: "Italy" },
  { url: "/JM", name: "Jamaica" },
  { url: "/JP", name: "Japan" },
  { url: "/JO", name: "Jordan" },
  { url: "/KZ", name: "Kazakhstan" },
  { url: "/KE", name: "Kenya" },
  { url: "/KP", name: "North Korea" },
  { url: "/KR", name: "South Korea" },
  { url: "/KW", name: "Kuwait" },
  { url: "/KG", name: "Kyrgyzstan" },
  { url: "/LA", name: "Laos" },
  { url: "/LV", name: "Latvia" },
  { url: "/LB", name: "Lebanon" },
  { url: "/LS", name: "Lesotho" },
  { url: "/LR", name: "Liberia" },
  { url: "/LY", name: "Libya" },
  { url: "/LI", name: "Liechtenstein" },
  { url: "/LT", name: "Lithuania" },
  { url: "/LU", name: "Luxembourg" },
  { url: "/MG", name: "Madagascar" },
  { url: "/MW", name: "Malawi" },
  { url: "/MY", name: "Malaysia" },
  { url: "/ML", name: "Mali" },
  { url: "/MT", name: "Malta" },
  { url: "/MR", name: "Mauritania" },
  { url: "/MU", name: "Mauritius" },
  { url: "/MX", name: "Mexico" },
  { url: "/MD", name: "Moldova" },
  { url: "/MN", name: "Mongolia" },
  { url: "/ME", name: "Montenegro" },
  { url: "/MA", name: "Morocco" },
  { url: "/MZ", name: "Mozambique" },
  { url: "/MM", name: "Myanmar" },
  { url: "/NA", name: "Namibia" },
  { url: "/NR", name: "Nauru" },
  { url: "/NP", name: "Nepal" },
  { url: "/NL", name: "Netherlands" },
  { url: "/NC", name: "New Caledonia" },
  { url: "/NZ", name: "New Zealand" },
  { url: "/NI", name: "Nicaragua" },
  { url: "/NE", name: "Niger" },
  { url: "/NG", name: "Nigeria" },
  { url: "/NO", name: "Norway" },
  { url: "/OM", name: "Oman" },
  { url: "/PK", name: "Pakistan" },
  { url: "/PS", name: "Palestine" },
  { url: "/PA", name: "Panama" },
  { url: "/PG", name: "Papua New Guinea" },
  { url: "/PY", name: "Paraguay" },
  { url: "/PE", name: "Peru" },
  { url: "/PH", name: "Philippines" },
  { url: "/PL", name: "Poland" },
  { url: "/PT", name: "Portugal" },
  { url: "/PR", name: "Puerto Rico" },
  { url: "/QA", name: "Qatar" },
  { url: "/MK", name: "North Macedonia" },
  { url: "/RO", name: "Romania" },
  { url: "/RU", name: "Russia" },
  { url: "/RW", name: "Rwanda" },
  { url: "/SA", name: "Saudi Arabia" },
  { url: "/SN", name: "Senegal" },
  { url: "/RS", name: "Serbia" },
  { url: "/SL", name: "Sierra Leone" },
  { url: "/SK", name: "Slovakia" },
  { url: "/SI", name: "Slovenia" },
  { url: "/SB", name: "Solomon Is." },
  { url: "/SO", name: "Somalia" },
  { url: "/ZA", name: "South Africa" },
  { url: "/SS", name: "S. Sudan" },
  { url: "/ES", name: "Spain" },
  { url: "/LK", name: "Sri Lanka" },
  { url: "/SD", name: "Sudan" },
  { url: "/SR", name: "Suriname" },
  { url: "/SE", name: "Sweden" },
  { url: "/CH", name: "Switzerland" },
  { url: "/SY", name: "Syria" },
  { url: "/TW", name: "Taiwan" },
  { url: "/TJ", name: "Tajikistan" },
  { url: "/TZ", name: "Tanzania" },
  { url: "/TH", name: "Thailand" },
  { url: "/TG", name: "Togo" },
  { url: "/TT", name: "Trinidad and Tobago" },
  { url: "/TN", name: "Tunisia" },
  { url: "/TR", name: "Turkey" },
  { url: "/TM", name: "Turkmenistan" },
  { url: "/UG", name: "Uganda" },
  { url: "/UA", name: "Ukraine" },
  { url: "/AE", name: "United Arab Emirates" },
  { url: "/GB", name: "United Kingdom" },
  { url: "/US", name: "United States of America" },
  { url: "/UY", name: "Uruguay" },
  { url: "/UZ", name: "Uzbekistan" },
  { url: "/VU", name: "Vanuatu" },
  { url: "/VE", name: "Venezuela" },
  { url: "/VN", name: "Vietnam" },
  { url: "/EH", name: "W. Sahara" },
  { url: "/YE", name: "Yemen" },
  { url: "/ZM", name: "Zambia" },
  { url: "/ZW", name: "Zimbabwe" }
];

export default countryCodeList;


